version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exach match is found
            - v1-dependencies-

      - run: mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          keys: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: /tmp/workspace
          paths: .
  docker-image_and-publish:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -a /tmp/workspace
      - run:
          name: Create Docker Image and Push to ECR
          command: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 689570751828.dkr.ecr.us-east-1.amazonaws.com && docker build -t ticketingdb . && docker tag ticketingdb:latest 689570751828.dkr.ecr.us-east-1.amazonaws.com/ticketingdb:latest && docker push 689570751828.dkr.ecr.us-east-1.amazonaws.com/ticketingdb:latest
  deploy-job:
    docker:
      #specify the version you desire here
      - image: circleci/node:10.0.0
    steps:
      - run:
          name: Execute Deployment Script
          command: |
            ssh -o "StrictHostKeyChecking=no" ec2-user@ec2-54-163-67-62.compute-1.amazonaws.com <<'ENDSSH'
            /bin/bash bin/deploy_image.sh
            docker ps
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - docker-image-and-publish:
          requires:
            - build
      - deploy-job:
          requires:
            - docker-image-and-publish